<%@ Page Title="Audit Logs" Language="C#" MasterPageFile="~/Admin.Master" AutoEventWireup="true" CodeBehind="AuditLogs.aspx.cs" Inherits="VelascoPersonalWebsite_IPT.Pages.Admin.AuditLogs" %>
<asp:Content ID="HeadContent" ContentPlaceHolderID="head" runat="server"><meta name="description" content="Registration and sign-in audit logs." /></asp:Content>
<asp:Content ID="MainContent" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <section aria-labelledby="auditLogsHeading"><div class="mb-3"><h1 id="auditLogsHeading" class="admin-page-title mb-2">Audit logs</h1><p class="text-secondary mb-0">Review registration and sign-in activity.</p></div>
        <section class="admin-panel" aria-labelledby="auditTableHeading"><div class="admin-panel-header border-bottom p-4"><h2 id="auditTableHeading" class="h5 fw-semibold mb-1">Recent events</h2><p class="small text-secondary mb-0">Search by username or email and filter by event type.</p></div>
            <div class="admin-toolbar p-4"><div class="row g-3 align-items-end"><div class="col-12 col-lg-7"><label class="form-label small fw-semibold" for="UserSearchTextBox">Search user</label><div class="input-group"><asp:TextBox ID="UserSearchTextBox" runat="server" CssClass="form-control" MaxLength="254" placeholder="Search by username or email" /><asp:Button ID="SearchButton" runat="server" Text="Search" CssClass="btn btn-dark" OnClick="SearchButton_Click" /></div></div><div class="col-12 col-lg-5"><label class="form-label small fw-semibold" for="EventTypeDropDownList">Filter by event type</label><div class="input-group"><asp:DropDownList ID="EventTypeDropDownList" runat="server" CssClass="form-select"><asp:ListItem Text="All event types" Value="All" /><asp:ListItem Text="Registration" Value="Registration" /><asp:ListItem Text="Sign in" Value="SignIn" /></asp:DropDownList><asp:Button ID="FilterButton" runat="server" Text="Apply" CssClass="btn btn-outline-dark" OnClick="FilterButton_Click" /><asp:Button ID="ClearButton" runat="server" Text="Clear" CssClass="btn btn-outline-secondary" OnClick="ClearButton_Click" CausesValidation="false" /></div></div></div></div>
            <asp:Literal ID="FeedbackLiteral" runat="server" />
            <div class="table-responsive"><table class="table admin-table align-middle mb-0"><thead><tr><th scope="col">User</th><th scope="col">Event type</th><th scope="col">Occurred (UTC)</th><th scope="col">Actions</th></tr></thead><tbody><asp:Repeater ID="AuditLogsRepeater" runat="server"><ItemTemplate><tr><td><strong><%#: Eval("User.Username") %></strong><br /><small><%#: Eval("User.Email") %></small></td><td><%# FormatEventType(Eval("EventType")) %></td><td><%# ((DateTime)Eval("OccurredUtc")).ToString("yyyy-MM-dd HH:mm") %></td><td><button type="button" class="admin-table-button">View details</button></td></tr></ItemTemplate></asp:Repeater></tbody></table></div>
        </section>
    </section>
</asp:Content>
