//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VelascoPersonalWebsite_IPT.Pages.Admin
{
    public partial class AuditLogs
    {
        protected global::System.Web.UI.WebControls.TextBox UserSearchTextBox;
        protected global::System.Web.UI.WebControls.Button SearchButton;
        protected global::System.Web.UI.WebControls.DropDownList EventTypeDropDownList;
        protected global::System.Web.UI.WebControls.Button FilterButton;
        protected global::System.Web.UI.WebControls.Button ClearButton;
        protected global::System.Web.UI.WebControls.Literal FeedbackLiteral;
        protected global::System.Web.UI.WebControls.Repeater AuditLogsRepeater;
    }
}
