//------------------------------------------------------------------------------
// <auto-generated>
//------------------------------------------------------------------------------
namespace VelascoPersonalWebsite_IPT.Pages.Admin
{
    public partial class Profile
    {
        protected global::System.Web.UI.WebControls.ValidationSummary ProfileValidationSummary;
        protected global::System.Web.UI.WebControls.Literal FeedbackLiteral;
        protected global::System.Web.UI.WebControls.TextBox GreetingNameTextBox;
        protected global::System.Web.UI.WebControls.TextBox IntroductionTextBox;
        protected global::System.Web.UI.WebControls.TextBox EmailTextBox;
        protected global::System.Web.UI.WebControls.TextBox LinkedInUrlTextBox;
        protected global::System.Web.UI.WebControls.TextBox GitHubUrlTextBox;
        protected global::System.Web.UI.WebControls.TextBox EducationHeadingTextBox;
        protected global::System.Web.UI.WebControls.TextBox EducationSummaryTextBox;
        protected global::System.Web.UI.WebControls.TextBox CurrentEducationPeriodTextBox;
        protected global::System.Web.UI.WebControls.TextBox CurrentEducationTitleTextBox;
        protected global::System.Web.UI.WebControls.TextBox CurrentEducationDescriptionTextBox;
        protected global::System.Web.UI.WebControls.TextBox PreviousEducationPeriodTextBox;
        protected global::System.Web.UI.WebControls.TextBox PreviousEducationTitleTextBox;
        protected global::System.Web.UI.WebControls.TextBox PreviousEducationDescriptionTextBox;
        protected global::System.Web.UI.WebControls.TextBox InterestsHeadingTextBox;
        protected global::System.Web.UI.WebControls.TextBox InterestsSummaryTextBox;
        protected global::System.Web.UI.WebControls.TextBox InterestOneTitleTextBox;
        protected global::System.Web.UI.WebControls.TextBox InterestOneDescriptionTextBox;
        protected global::System.Web.UI.WebControls.TextBox InterestTwoTitleTextBox;
        protected global::System.Web.UI.WebControls.TextBox InterestTwoDescriptionTextBox;
        protected global::System.Web.UI.WebControls.TextBox InterestThreeTitleTextBox;
        protected global::System.Web.UI.WebControls.TextBox InterestThreeDescriptionTextBox;
        protected global::System.Web.UI.WebControls.TextBox SkillsEyebrowTextBox;
        protected global::System.Web.UI.WebControls.TextBox SkillsHeadingTextBox;
        protected global::System.Web.UI.WebControls.TextBox SkillsSummaryTextBox;
        protected global::System.Web.UI.WebControls.TextBox SkillsTextBox;
        protected global::System.Web.UI.WebControls.TextBox ContactHeadingTextBox;
        protected global::System.Web.UI.WebControls.TextBox ContactDescriptionTextBox;
        protected global::System.Web.UI.WebControls.TextBox FooterStatementTextBox;
        protected global::System.Web.UI.WebControls.TextBox FooterEmailTextBox;
        protected global::System.Web.UI.WebControls.TextBox FooterPhoneTextBox;
        protected global::System.Web.UI.WebControls.TextBox FooterGitHubTextBox;
        protected global::System.Web.UI.WebControls.TextBox FooterLinkedInTextBox;
        protected global::System.Web.UI.WebControls.Button SaveButton;
    }
}
