//------------------------------------------------------------------------------
// <auto-generated>
//------------------------------------------------------------------------------
namespace VelascoPersonalWebsite_IPT.Pages.Admin
{
    public partial class UserDetails
    {
        protected global::System.Web.UI.WebControls.Literal FeedbackLiteral;
        protected global::System.Web.UI.WebControls.Panel DetailsPanel;
    }
}
